import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendor-generated by `shadcn add` / Next.js scaffold; do not edit.
    "components/ui/**",
    "hooks/use-mobile.ts",
    "skills/**",
    // Generated, gitignored test artifacts — Playwright's HTML report bundles
    // minified vendor JS that eslint would otherwise flag by the thousands.
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
    // Gitignored Storybook build output — minified vendor bundles.
    "storybook-static/**",
  ]),
]);

export default eslintConfig;
